// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'dart:io';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/foundation.dart' show Platform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isIOS) {
      return ios;
    } else if (Platform.isAndroid) {
      return android;
    }
    throw UnsupportedError('Unsupported platform');
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoQBXPsoJsRPAphrKVsL4_9Wrw4C_Fdaw',
    appId: '1:65737008436:android:11a9779e6de238c8d53161',
    messagingSenderId: '65737008436',
    projectId: 'chatapp-995bc',
    storageBucket: 'chatapp-995bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmgilWyUSjQ_tOT0KgRd_e33XI2_AKv2k',
    appId: '1:65737008436:ios:cd7dcd7bcbb1deded53161',
    messagingSenderId: '65737008436',
    projectId: 'chatapp-995bc',
    storageBucket: 'chatapp-995bc.firebasestorage.app',
    iosBundleId: 'com.firebase.chatapp.firebaseChatApp',
  );
}
